[env]
MISERUN_SHELL = "powershell"

[tools]
python = "3.11"
node = "lts"

[tasks.api]
run = [
  "cd so-momeet/backend",
  "uv venv --python 3.11",
  "uv pip install -e .[dev]",
  "uv run somomeet-api",
]

[tasks.test]
run = [
  "cd so-momeet/backend",
  "uv run pytest -q",
]

[tasks.admin]
run = [
  "cd so-momeet/admin",
  "uv venv --python 3.11",
  "uv pip install -e .",
  "uv run django-admin --version",
]

[tasks.mobile]
run = [
  "cd so-momeet/mobile",
  "if (!(Test-Path package.json)) { npm init -y }",
  "if (!(Test-Path node_modules)) { npm install expo react-native }",
  "echo 'Open Expo project in this folder'",
]
