[project]
name = "somomeet-admin"
version = "0.1.0"
requires-python = ">=3.11"

[tool.uv]
index-url = "https://pypi.org/simple"

[dependency-groups]
main = [
  "Django>=5.0",
  "psycopg2-binary",
]

dev = [
  "ruff",
  "black",
]
